// Module included in the following assemblies:
//
// assembly-dedicated-nodes.adoc

[id='proc-dedicated-nodes-{context}']
= Setting up dedicated nodes and scheduling pods on them

.Prerequisites

* {AProductPlatformName} cluster
* A running Cluster Operator

.Procedure

. Select the nodes which should be used as dedicated.
. Make sure there are no workloads scheduled on these nodes.
. Set the taints on the selected nodes:
+
ifdef::Kubernetes[]
On {KubernetesName} this can be done using `kubectl taint`:
[source,shell,subs=+quotes]
kubectl taint node _your-node_ dedicated=Kafka:NoSchedule
+
endif::Kubernetes[]
ifdef::OpenShift[]
On {OpenShiftName} this can be done using `oc adm taint`:
+
[source,shell,subs=+quotes]
oc adm taint node _your-node_ dedicated=Kafka:NoSchedule
+
endif::OpenShift[]
. Additionally, add a label to the selected nodes as well.
+
This can be done using `{cmdcli} label`:
[source,shell,subs="+quotes,attributes+"]
{cmdcli} label node _your-node_ dedicated=Kafka
+
. Edit the `affinity` and `tolerations` properties in the resource specifying the cluster deployment.
For example:
+
[source,yaml,subs=attributes+]
----
apiVersion: {KafkaApiVersion}
kind: Kafka
spec:
  kafka:
    # ...
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "Kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - Kafka
    # ...
  zookeeper:
    # ...
----

. Create or update the resource.
+
This can be done using `{cmdcli} apply`:
[source,shell,subs="+quotes,attributes+"]
{cmdcli} apply -f _your-file_
